const data = [
  {
    name: "agregat uprawowo-przedsiewny Euro-Masz(AU)",
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/agregaty-uprawowe/euro-maszau",
    id: 1,
  },
  {
    name: "agregat uprawowy ciężki Euro-Masz(AUC)",
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/agregaty-uprawowe/euro-maszauc",
    id: 2,
  },
  {
    name: `agregat uprawowy "nietoperek" strumyk`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/agregaty-uprawowe/nietoperek",
    id: 3,
  },
  {
    name: `agregat uprawowy "neon" Tolmet`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/agregaty-uprawowe/neon",
    id: 4,
  },
  {
    name: `agregat uprawowo-siewny (AS) z hydropakiem Euro-Masz`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/agregaty-uprawowo-siewne/euro-masz-as",
    id: 5,
  },
  {
    name: `agregat uprawowo-siewny bez hydropaku Armasz`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/agregaty-uprawowo-siewne/armasz-bez-hydropaku",
    id: 6,
  },
  {
    name: `agregat uprawowo-siewny z hydropakiem 1 wał armasz`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/agregaty-uprawowo-siewne/armasz-hydropak-1",
    id: 7,
  },
  {
    name: `agregat uprawowo-siewny z hydropakiem 2 wały armasz`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/agregaty-uprawowo-siewne/armasz-hydropak-2",
    id: 8,
  },
  {
    name: `agregat uprawowo-siewny "polonek" Tolmet`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/agregaty-uprawowo-siewne/polonek",
    id: 9,
  },
  {
    name: `agregat uprawowo-siewny "polon s" Tolmet`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/agregaty-uprawowo-siewne/polons",
    id: 10,
  },
  {
    name: `agregat uprawowo-siewny "polon" Tolmet`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/agregaty-uprawowo-siewne/polon",
    id: 11,
  },
  {
    name: `agregat talerzowy z hydropakiem Euro-Masz`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/agregaty-uprawowe-hydropak/talerz-euro",
    id: 12,
  },
  {
    name: `agregat talerzowy z hydropakiem lekki Armasz`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/agregaty-uprawowe-hydropak/talerz-lekki-armasz",
    id: 13,
  },
  {
    name: `agregat talerzowy ciężki z hydropakiem Armasz`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/agregaty-uprawowe-hydropak/talerz-ciezki-armasz",
    id: 14,
  },
  {
    name: `agregat talerzowy ciężki bez hydropaku Armasz`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/agregaty-uprawowe-hydropak/talerz-bez-hydropaku-armasz",
    id: 15,
  },
  {
    name: `agregat talerzowy z hydropakiem "tytan" Tolmet`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/agregaty-uprawowe-hydropak/talerz-tytan",
    id: 16,
  },

  {
    name: `agregat talerzowy z pakiem "tytan" z wałem oponowym`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/agregaty-uprawowe-hydropak/talerz-tytan-z-walem",
    id: 17,
  },
  {
    name: `agregat talerzowy z pakiem "tiger" Strumyk`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/agregaty-uprawowe-hydropak/talerz-tiger",
    id: 18,
  },
  {
    name: `brona talerzowa "alfX Strumyk`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/brony-talerzowe/alfa",
    id: 19,
  },
  {
    name: `brona talerzowa zawieszana w układzie "V" Selmar`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/brony-talerzowe/zawieszana",
    id: 20,
  },
  {
    name: `brona talerzowa "tiger junior" Strumyk`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/brony-talerzowe/tiger-jr",
    id: 21,
  },
  {
    name: `brona talerzowa "tiger II" Strumyk`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/brony-talerzowe/tiger-ii",
    id: 22,
  },
  {
    name: `brona talerzowa "mega" rozstaw 1200cm Strumyk`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/brony-talerzowe/mega-rozstaw",
    id: 23,
  },
  {
    name: `brona talerzowa hydrauliczna "tiger" Strumyk`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/brony-talerzowe/hydrauliczna-tiger",
    id: 24,
  },
  {
    name: `brona talerzowa hydrauliczna ciężka "rotos"`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/brony-talerzowe/hydrauliczna-ciezka-rotos",
    id: 25,
  },
  {
    name: `brona talerzowa Euro-masz(bt)`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/brony-talerzowe/euro-masz-bt",
    id: 26,
  },
  {
    name: `brona talerzowa ciężka poszerzona Euro-masz`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/brony-talerzowe/poszerzona-euro-masz",
    id: 27,
  },
  {
    name: `brona talerzowa pół zawieszana(btp) Euro-masz`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/brony-talerzowe/pol-zawieszana-euro-masz",
    id: 28,
  },
  {
    name: `brona talerzowa ciężka hydraulicznie rozkładana(BTCH)Euro-masz`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/brony-talerzowe/hydraulicznie-rozkladana-euro-masz",
    id: 29,
  },
  {
    name: `brona talerzowa ciężka zab. sprężynowe(BTCS)Euro-masz`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/brony-talerzowe/zab-sprezynowe-euro-masz",
    id: 30,
  },
  {
    name: `brona talerzowa hydraulicznie składana zawieszana Armasz`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/brony-talerzowe/hydraulicznie-skladana-zawieszana-armasz",
    id: 31,
  },
  {
    name: `brona talerzowa hydraulicznie składana z wózkiem transportowym Armasz`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/brony-talerzowe/hydraulicznie-skladana-z-wozkiem-armasz",
    id: 32,
  },
  {
    name: `brona talerzowa kompaktowa "simply" tolmet`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/brony-talerzowe/kompaktowa-simply-tolmet",
    id: 33,
  },
  {
    name: `brona talerzowa kompaktowa "astat" tolmet`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/brony-talerzowe/kompaktowa-astat-tolmet",
    id: 34,
  },
  {
    name: `brona talerzowa kompaktowa "astat" z urządzeniem trakcyjnym model I tolmet`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/brony-talerzowe/kompaktowa-astat-model-I-tolmet",
    id: 35,
  },
  {
    name: `brona talerzowa kompaktowa "astat" z urządzeniem trakcyjnym model II tolmet`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/brony-talerzowe/kompaktowa-astat-model-II-tolmet",
    id: 36,
  },
  {
    name: `brona talerzowa kompaktowa "tenes" z urządzeniem trakcyjnym model I tolmet`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/brony-talerzowe/kompaktowa-tenes-model-I-tolmet",
    id: 37,
  },
  {
    name: `brona kompaktowa hydraulicznie składana "megatron" tolmet`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/brony-talerzowe/kompaktowa-megatron-tolmet",
    id: 38,
  },
  {
    name: `brona kompaktowa hydraulicznie składana "megatron" tolmet`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/brony-talerzowe/kompaktowa-megatron-tolmet",
    id: 39,
  },
  {
    name: `brona kompaktowa hydraulicznie składana "megatron" XL tolmet`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/brony-talerzowe/kompaktowa-megatron-xl-tolmet",
    id: 40,
  },
  {
    name: `brona kompaktowa "tenes" tolmet`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/brony-talerzowe/kompaktowa-tenes-tolmet",
    id: 41,
  },
  {
    name: `brona aktywna wir tolmet`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/brony-talerzowe/aktywna-wir-tolmet",
    id: 42,
  },
  {
    name: `Agregat podrywkowy "gruber" zab zrywalne Euro-masz`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/agregaty-podrywkowe/zab-zrywalne-euro-masz",
    id: 43,
  },
  {
    name: `Agregat podrywkowy "gruber" zab ślimakowe Euro-masz`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/agregaty-podrywkowe/zab-slimakowe-euro-masz",
    id: 44,
  },
  {
    name: `Agregat podrywkowy "gruber" zab sprężynowe`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/agregaty-podrywkowe/zab-sprezynowe",
    id: 45,
  },
  {
    name: `Agregat ścierniskowy zab kołkowe Armasz`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/agregaty-podrywkowe/zab-kolkowe-armasz",
    id: 46,
  },
  {
    name: `Agregat ścierniskowy zab ślimakowe Armasz`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/agregaty-podrywkowe/zab-slimakowe-armasz",
    id: 47,
  },
  {
    name: `Agregat ścierniskowy zab sprężynowe Armasz`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/agregaty-podrywkowe/zab-sprezynowe-armasz",
    id: 48,
  },
  {
    name: `Agregat podrywkowy "krypton" Tolmet`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/agregaty-podrywkowe/krypton-tolmet",
    id: 49,
  },
  {
    name: `Agregat podrywkowy "arsen" Tolmet`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/agregaty-podrywkowe/arsen-tolmet",
    id: 50,
  },
  {
    name: `kultywator ścierniskowy Tolmet`,
    imgUrl: "images/dji-5331597_1280.jpg",
    searcherImg: "images/logo.jpg",
    route: "/agregaty-podrywkowe/kultywator-tolmet",
    id: 51,
  },
];
export default data;
